### ISSUE TITLE
[Ported Feature] Moderation commands

### ISSUE THREAD

**Issue by sr229** [owo-dev-team/owo-whats-this#11]
for those lazy twats who can't do role-changing and banning and kicking themselves

**TODO**
- [x] Mention-to-ban/kick/mute system (Partial : 2 out of 3 functions implemented)
- [ ] Mention-to-add/remove role
- [x] go awau (optional)

**Comment by sr229** [comment]
Already handled on refactor, Closed.
