### ISSUE TITLE
Port to Eris

### ISSUE THREAD

**Issue by Ovyerus** [owo-dev-team/owo-whats-this#33]
### TODO-a-fuckton-list 9000
- [ ] Rewrite commands (Music is the most painful)
- [ ] dereference d.js from everything and use Eris methods/functions.
- [ ] smoke weed xX420BlazEiTxX

**Comment by sr229** [comment]
added TODO list 


we on boiz

**Comment by Ovyerus** [comment]
Done in #21
